name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest # TODO enable minor version tags / pinning
    
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Test
      run: cargo test
    
    - name: Build
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: hovercrafter-linux
        path: ${{ github.workspace }}/target/release/main


  build-windows:
    runs-on: windows-latest
    steps:
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install GTK4
      run: |
        choco install -y vcpkg
        vcpkg install gtk:x64-windows

    - name: Set up environment variables
      run: |
        echo "VCPKG_ROOT=C:\\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "GTK4_DIR=C:\\vcpkg\\installed\\x64-windows" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "PKG_CONFIG_PATH=C:\\vcpkg\\installed\\x64-windows\\lib\\pkgconfig" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Path=C:\\vcpkg\\installed\\x64-windows\\bin;$env:Path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    
    - name: Build
      run: cargo build --release
      shell: cmd
    
    - uses: actions/upload-artifact@v4
      with:
        name: hovercrafter-linux
        path: ${{ github.workspace }}/target/release/main
