name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest # TODO enable minor version tags / pinning
    
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Test
      run: cargo test
    
    - name: Build
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: hovercrafter-linux
        path: ${{ github.workspace }}/target/release/main


  build-windows:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install MSYS2 and GTK4
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gtk4
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-cmake
        update: true

    - name: Set Environment Variables
      run: |
        echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
        echo "CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
      shell: bash
    
    - name: Build
      shell: cmd
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: hovercrafter-linux
        path: ${{ github.workspace }}/target/release/main
