name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest # TODO enable minor version tags / pinning
    
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Test
      run: cargo test
    
    - name: Build
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: hovercrafter-linux
        path: ${{ github.workspace }}/target/release/main


  build-windows:
    runs-on: windows-latest
    steps:

    - name: Install MSYS2 and GTK4
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gtk4 
          mingw-w64-x86_64-gettext 
          mingw-w64-x86_64-libxml2 
          mingw-w64-x86_64-librsvg 
          mingw-w64-x86_64-pkgconf 
          mingw-w64-x86_64-gcc
        update: true
    
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set Environment Variables
      run: |
        echo "CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1" >> $GITHUB_ENV
        echo "CARGO_PKG_CONFIG=pkg-config" >> $GITHUB_ENV
        echo "PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\msys64\mingw64\include;$env:PATH" >> $GITHUB_ENV
    
    - name: Setup GNU toolchain for Rust
      run: |
        rustup toolchain install stable-gnu
        rustup default stable-gnu
    
    - name: Build
      run: cargo build --release
    
    - uses: actions/upload-artifact@v4
      with:
        name: hovercrafter-linux
        path: ${{ github.workspace }}/target/release/main
